[package]
name = "to_do"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.22.1"
serde_json = "1.0.60"
serde = { version = "1.0", features = ["derive"] }